server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

accounts:
    message: "Welcome to EazyBank accounts related local APIs "
    contactDetails:
        name: "John Doe - Developer"
        email: "john@eazybank.com"
    onCallSupport:
        - (555) 555-1234
        - (555) 523-1345
    cloud:
        stream:
            bindings:
                sendCommunication-out-0:
                    destination: send-communication
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        connection-timeout: 10s